---
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Rails:
  Enabled: true

Layout/LineLength:
  Max: 125

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/ExampleLength:
  Max: 10

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
