---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - db/schema.rb
    - bin/bundle
    - vendor/**/*

Rails:
  Enabled: true
  Exclude:
    - bin/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

RSpec/ExampleLength:
  Max: 10

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
