default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-template_development
  #username: rails-template
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice
test:
  <<: *default
  database: rails-template_test
production:
  <<: *default
  database: rails-template_production
  username: rails-template
  password: <%= ENV['RAILS-TEMPLATE_DATABASE_PASSWORD'] %>
